id: P009389
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14621
  title: སློབ་དཔོན་པདྨ་འབྱུང་གནས་དང་བྱང་པ་རྣམ་རྒྱལ་གྲགས་བཟང་གི་རྣམ་ཐར།
  author: ''
  volumes:
    7dfb61a9b4b14aa2a28b06a935f341b3:
      image_group_id: I1KG15631
      title: ''
      volume_number: 1
      total_pages: 320
