id: I913E4457
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T09:23:49+00:00'
last_modified: '2022-06-08T10:40:00.911557+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14621
  title: སློབ་དཔོན་པདྨ་འབྱུང་གནས་དང་བྱང་པ་རྣམ་རྒྱལ་གྲགས་བཟང་གི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BF9B:
      image_group_id: I1KG15631
      title: ''
      total_pages: 320
      order: 1
      base_file: BF9B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
